import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ErrorWrapper } from "./error.wrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  home,
  contact
}: Readonly<{
  children: React.ReactNode;
  home: React.ReactNode;
  contact: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="bg-blue-600 text-blue-300 p-4">
          <p>Header</p>
        </header>
        <ErrorWrapper>
          {children}
        </ErrorWrapper>
        {home}
        {contact}

        <footer className="bg-lime-600 text-lime-300 p-4">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
